name: demo api tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  notifyTelegram:
    runs-on: ubuntu-latest
    steps:
    - name: send custom message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          A new commit has been pushed.

  tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: testReport
        path: |
          test-report.html

  allure_reports_pages:
    runs-on: ubuntu-latest
    steps:
    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Test marketplace action
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: build/allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-results

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.PAGES_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-results
